# Generated by Django 2.1.7 on 2019-03-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fovoriteescorts',
            name='escorts',
        ),
        migrations.RemoveField(
            model_name='fovoriteescorts',
            name='user',
        ),
        migrations.DeleteModel(
            name='FovoriteEscorts',
        ),
    ]
