# Generated by Django 2.1.7 on 2019-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190309_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escorts',
            field=models.ManyToManyField(related_name='_user_escorts_+', to='core.Escort'),
        ),
    ]
