# Generated by Django 2.1.8 on 2019-04-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_escorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='escorts',
        ),
    ]
