# Generated by Django 2.1.9 on 2019-08-12 05:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_escorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='contact_line',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='escort',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='escort',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='escort',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='escort',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='escort',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='escort',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
        migrations.AddField(
            model_name='escort',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escort',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='escort',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='escort',
            name='shape',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='escort',
            name='status',
            field=models.CharField(default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='escort',
            name='viewscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escort',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='escort',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.escort_image_file_path),
        ),
    ]
