# Generated by Django 2.1.9 on 2019-08-12 06:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190812_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.escort_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.user_image_file_path),
        ),
    ]
